sonar.projectKey=t-esp-800-project-71802-par_augmentedbotbattle
sonar.qualitygate.wait=true

# Garder l'analyse concentrée sur les vraies sources
sonar.inclusions=project/Backend/BackendESP/**,project/Unity/ABB/**

# Exclure les dossiers lourds / générés
sonar.exclusions=**/Library/**,**/Temp/**,**/Obj/**,**/Build/**,**/build/**,**/*.png,**/*.fbx,**/*.mp4

# YAML (si tu veux analyser les YAML)
sonar.yaml.activate=true
sonar.yaml.file.suffixes=.yml,.yaml
# C# (si tu veux analyser le backend .NET)
sonar.cs.opencover.reportsPaths=reports/coverage/*.xml
sonar.cs.fxcop.reportsPaths=reports/coverage/*.xml